# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 884ea59b776be2d6fe9b517b871a32fdf0f269a7422f487cac38dffa314e1c7135dd07c8de6c7235f6bb362e64b7aeef1142c6e92238100caa7bdb733bb94ddc

test:
  secret_key_base: 8d0ade1092651296e62a2523b94c57b2f59f1ad2d698fff6a2203f7b481f97334d2f61e18b3c317bec53ae649301f964cbb75794ed8b4bd74444338472d2121d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
